# Generated by Django 4.0.6 on 2022-08-09 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Closing',
            fields=[
                ('noteid', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.TimeField()),
                ('distance', models.IntegerField()),
                ('location', models.CharField(max_length=150)),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/2022/08/09/', verbose_name='Фото 1')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/2022/08/09/', verbose_name='Фото 2')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/2022/08/09/', verbose_name='Фото 3')),
                ('date', models.DateField(max_length=50)),
            ],
            options={
                'verbose_name': 'Закрытые заявки',
                'verbose_name_plural': 'Закрытые заявки',
            },
        ),
        migrations.CreateModel(
            name='ClosingStatus',
            fields=[
                ('statusid', models.IntegerField(primary_key=True, serialize=False)),
                ('definition', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Статусы закрытых заявок',
                'verbose_name_plural': 'Статусы закрытых заявок',
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('objectid', models.IntegerField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=150, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('objecttype', models.CharField(max_length=20, null=True)),
                ('radius', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('workerid', models.IntegerField(primary_key=True, serialize=False)),
                ('tabel', models.IntegerField(null=True)),
                ('fullname', models.CharField(max_length=50, null=True)),
                ('post', models.CharField(max_length=20, null=True)),
                ('coeff', models.FloatField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Монтажник',
                'verbose_name_plural': 'Монтажники',
            },
        ),
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('openid', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(max_length=50)),
                ('time', models.TimeField()),
                ('location', models.CharField(max_length=150)),
                ('distance', models.IntegerField()),
                ('objectid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='top.object')),
                ('workerid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='top.worker')),
            ],
            options={
                'verbose_name': 'Открытые заявки',
                'verbose_name_plural': 'Открытые заявки',
            },
        ),
        migrations.CreateModel(
            name='DataToExport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spended_time', models.FloatField(verbose_name='Потрачено времени')),
                ('closedate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='top.closing', verbose_name='Закрыто')),
                ('object_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='top.object', verbose_name='Объект')),
                ('opendate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='top.opening', verbose_name='Окрыто')),
                ('worker_fullname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='top.worker', verbose_name='ФИО')),
            ],
            options={
                'verbose_name': 'Отчёт в Excel',
                'verbose_name_plural': 'Отчёт в Excel',
            },
        ),
        migrations.AddField(
            model_name='closing',
            name='openid',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='top.opening'),
        ),
        migrations.AddField(
            model_name='closing',
            name='statusid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='top.closingstatus'),
        ),
    ]
