# Generated by Django 4.0.6 on 2022-08-09 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('top', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closing',
            name='openid',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='top.opening'),
        ),
        migrations.AlterField(
            model_name='closing',
            name='statusid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='top.closingstatus'),
        ),
        migrations.AlterField(
            model_name='opening',
            name='objectid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='top.object'),
        ),
        migrations.AlterField(
            model_name='opening',
            name='workerid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='top.worker'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
