# Generated by Django 4.0.6 on 2022-08-09 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0003_alter_datatoexport_closedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatoexport',
            name='closedate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='top.closing', verbose_name='Закрыто'),
        ),
        migrations.AlterField(
            model_name='datatoexport',
            name='opendate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='top.opening', verbose_name='Окрыто'),
        ),
        migrations.AlterField(
            model_name='datatoexport',
            name='spended_time',
            field=models.TimeField(verbose_name='Потрачено времени'),
        ),
    ]
