# Generated by Django 4.0.6 on 2022-08-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0004_alter_datatoexport_closedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatoexport',
            name='closedate',
            field=models.DateField(verbose_name='Закрыто'),
        ),
        migrations.AlterField(
            model_name='datatoexport',
            name='opendate',
            field=models.DateField(verbose_name='Окрыто'),
        ),
    ]
