# Generated by Django 4.0.6 on 2022-08-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0006_alter_datatoexport_object_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatoexport',
            name='spended_time',
            field=models.DateField(verbose_name='Затраченное время'),
        ),
    ]
