# Generated by Django 4.0.6 on 2022-08-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0007_alter_datatoexport_spended_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatoexport',
            name='spended_time',
            field=models.CharField(max_length=25, verbose_name='Затраченное время'),
        ),
    ]
