# Generated by Django 4.0.6 on 2022-08-10 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0009_totalspendedtimeonobject_alter_closing_photo_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalspendedtimeonobject',
            name='closedate',
        ),
        migrations.RemoveField(
            model_name='totalspendedtimeonobject',
            name='opendate',
        ),
    ]
