# Generated by Django 4.0.6 on 2022-08-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0010_remove_totalspendedtimeonobject_closedate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closing',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='photos/2022/08/12/', verbose_name='Фото 1'),
        ),
        migrations.AlterField(
            model_name='closing',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to='photos/2022/08/12/', verbose_name='Фото 2'),
        ),
        migrations.AlterField(
            model_name='closing',
            name='photo_3',
            field=models.ImageField(blank=True, upload_to='photos/2022/08/12/', verbose_name='Фото 3'),
        ),
    ]
