# Generated by Django 4.0.6 on 2022-08-12 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0011_alter_closing_photo_1_alter_closing_photo_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalspendedtimeonobject',
            name='spended_time',
            field=models.TimeField(verbose_name='Затраченное время'),
        ),
    ]
