# Generated by Django 4.0.6 on 2022-08-12 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top', '0012_alter_totalspendedtimeonobject_spended_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalspendedtimeonobject',
            name='spended_time',
            field=models.CharField(max_length=25, verbose_name='Затраченное время'),
        ),
    ]
